export const appText = {
  editTopic: "編輯題目",
  choostYear: "請選擇年度",
  choostYearButton: "年度",
  choostAddTopicCategory: "請先選擇欲新增的題目類別(必選)",
  choostAddTopicCategoryButton: [
    "第一層分類",
    "第二層分類",
    "第三層分類",
    "第四層分類",
    "第五層分類",
  ],
  inquiry: "查詢",
  labelManagement: "管理標籤",
  topicCategory: "題目分類",
  year: "年度",
  grade: "年級",
  addCategory: "新增分類",
  rename: "重新命名",
  delete: "刪除",
  deleteDescription:
    "刪除此分類將會連同下方的所有子分類一併刪除，確定要刪除分類？",
  cancel: "取消",
  singleTopic: "單選題",
  multipleTopic: "多選題",
  fillTopic: "選填題",
  textEdit: "文字編輯",
  chooseTopicType: "選擇題目類型",
  correctAnswer: "正確答案(必填)",
  add: "新增",
  edit: "編輯",
  deleteTopic: "確定要刪除題目嗎？",
  uploadFile: "上傳檔案",
  question: "出題",
  backpage: "回上一頁",
  choosedTopic: "已選題目",
  haventChoosed: "尚未選取",
  chooseTopic: "選擇題目",
  previewTopic: "預覽考題",
  choosePaperType: "請選擇你的考卷類型",
  enterStudentName: "請輸入考生姓名",

  paperType: "考卷類型",
  previewPaper: "預覽考卷",

  enterUnitName: "請輸入單元名稱",
  enterPaperNumber: "請輸入考卷編號",
  repeatAnswerNumber: "考卷編號重複",
  allocation: "配分",
  paperInformation: "考卷資訊",
  singleAllocation: "單選題配分",
  multipleAllocation: "多選題配分",
  fillAllocation: "選填題配分",
  enterPropotion: "輸入比例(%)",
  topic: "題目",
  answerDetail: "答案詳解",
  topicAndAnswerDetail: "題目與答案詳解",
  downloadTopic: "下載題目",
  ensure: "確定",
  enterFalse: "輸入錯誤",
  studentName: "學生名字",
  faultType: "答錯題型",
  answerNumber: "答案編號",
  score: "分數",
  chooseTopicNumber: "選擇題數",
  topicNumber: "題數",
  login: "登入",
  enterAccount: "輸入帳號",
  enterPassword: "輸入密碼",
  testAccount: "測試帳號",
  testPassword: "測試密碼",
  logout: "登出",
};
